<?xml version="1.0" encoding="utf-8"?>
<Database Name="TestGuruDB" Class="TestGuruDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=BrunoPC\SQLEXPRESS2008EX;Initial Catalog=TestGuruDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TestGuruDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="Articles.Articles" Member="Articles">
    <Type Name="Article">
      <Column Name="ArticleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AuthorID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Tags" Type="System.String" DbType="VarChar(600)" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShowCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AverageGrade" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="GradesCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Content" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Article_Attachment" Member="Attachments" ThisKey="ArticleID" OtherKey="ArticleID" Type="Attachment" />
      <Association Name="Article_Comment" Member="Comments" ThisKey="ArticleID" OtherKey="ArticleID" Type="Comment" />
      <Association Name="Account_Article" Member="Account" ThisKey="AuthorID" OtherKey="ID" Type="Account" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="Auth.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Administrator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Role_AccountRole" Member="AccountRoles" ThisKey="ID" OtherKey="Role" Type="AccountRole" />
      <Association Name="Role_PermissionRole" Member="PermissionRoles" ThisKey="ID" OtherKey="Role" Type="PermissionRole" />
    </Type>
  </Table>
  <Table Name="Articles.Attachments" Member="Attachments">
    <Type Name="Attachment">
      <Column Name="ArticleID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FileID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Article_Attachment" Member="Article" ThisKey="ArticleID" OtherKey="ArticleID" Type="Article" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="UserFile_Attachment" Member="UserFile" ThisKey="FileID" OtherKey="FileID" Type="UserFile" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="Articles.Comments" Member="Comments">
    <Type Name="Comment">
      <Column Name="CommentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ArticleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AuthorID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PostDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Content" Type="System.String" DbType="VarChar(2000) NOT NULL" CanBeNull="false" />
      <Association Name="Article_Comment" Member="Article" ThisKey="ArticleID" OtherKey="ArticleID" Type="Article" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Account_Comment" Member="Account" ThisKey="AuthorID" OtherKey="ID" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Articles.UserFiles" Member="UserFiles">
    <Type Name="UserFile">
      <Column Name="FileID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OwnerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Size" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FilePath" Type="System.String" DbType="VarChar(280) NOT NULL" CanBeNull="false" />
      <Column Name="DisplayedName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="UserFile_Attachment" Member="Attachments" ThisKey="FileID" OtherKey="FileID" Type="Attachment" />
      <Association Name="Account_UserFile" Member="Account" ThisKey="OwnerID" OtherKey="ID" Type="Account" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="Auth.AccountRole" Member="AccountRoles">
    <Type Name="AccountRole">
      <Column Name="Account" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Role" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Role_AccountRole" Member="Role1" ThisKey="Role" OtherKey="ID" Type="Role" IsForeignKey="true" />
      <Association Name="Account_AccountRole" Member="Account1" ThisKey="Account" OtherKey="ID" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Auth.Permission" Member="Permissions">
    <Type Name="Permission">
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Permission_PermissionRole" Member="PermissionRoles" ThisKey="Name" OtherKey="Permission" Type="PermissionRole" />
    </Type>
  </Table>
  <Table Name="Auth.PermissionRole" Member="PermissionRoles">
    <Type Name="PermissionRole">
      <Column Name="Permission" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Role" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Permission_PermissionRole" Member="Permission1" ThisKey="Permission" OtherKey="Name" Type="Permission" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Role_PermissionRole" Member="Role1" ThisKey="Role" OtherKey="ID" Type="Role" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="Auth.RestrictedEmail" Member="RestrictedEmails">
    <Type Name="RestrictedEmail">
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Blocked" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="Auth.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.Data.Linq.Binary" DbType="Binary(16) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PasswordQuestion" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordAnswer" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ActivationGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="TerminationGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Account_Article" Member="Articles" ThisKey="ID" OtherKey="AuthorID" Type="Article" />
      <Association Name="Account_Comment" Member="Comments" ThisKey="ID" OtherKey="AuthorID" Type="Comment" />
      <Association Name="Account_UserFile" Member="UserFiles" ThisKey="ID" OtherKey="OwnerID" Type="UserFile" />
      <Association Name="Account_AccountRole" Member="AccountRoles" ThisKey="ID" OtherKey="Account" Type="AccountRole" />
    </Type>
  </Table>
</Database>